# Generated by Django 3.2.16 on 2025-01-15 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal', 'Юридическое лицо')], max_length=20, verbose_name='Тип клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('description', models.TextField(verbose_name='Описание тарифа')),
                ('price_per_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена за кВтч')),
                ('fixed_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фиксированный платеж')),
                ('payment_method', models.CharField(choices=[('per_kwh', 'Цена за кВтч'), ('fixed', 'Фиксированный платеж'), ('complex', 'Сложный тариф')], max_length=20, verbose_name='Метод оплаты')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Показания счетчика')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заявки')),
                ('payment_due_date', models.DateField(verbose_name='Дата оплаты')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма к оплате')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='tariff.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tariff.tariff', verbose_name='Тариф'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
