# Generated by Django 3.2.16 on 2025-01-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_tariff_is_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('-name',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
    ]
