# Generated by Django 3.2.16 on 2025-01-15 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0003_alter_tariff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на оплату', 'verbose_name_plural': 'Заявки на оплату'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ('-created_at',), 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AddField(
            model_name='client',
            name='contract_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Номер договора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
    ]
