# Generated by Django 3.2.16 on 2025-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_auto_20250115_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='payment_method',
            field=models.CharField(choices=[('per_kwh', 'Цена за кВтч'), ('fixed', 'Фиксированный платеж')], max_length=20, verbose_name='Метод оплаты'),
        ),
    ]
