# Generated by Django 3.2.16 on 2025-01-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0005_alter_tariff_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='Просрочено'),
        ),
    ]
